### PR TITLE
Worked on enjs folder change

### PR DESCRIPTION
**Pull request by Ndohjapan**
I simply changed the folder location of the `en.js` file to the `utils` folder.

### CODE REVIEW

**Comment by lennyAiko** [comment]
```diff
- <script src="./dist/main.js"></script>
+ <script type="module" src="./src/index.js"></script>
```

I noticed you made this change, does this mean you found a way for the code to work aside webpack?

**Comment by lennyAiko** [comment]
Also, `number-validator.js` was renamed to `check-format.js`

Your PR states otherwise. Did you update your local?

**Comment by Ndohjapan** [comment]
I think you can close this PR.

I discovered I started working on it before you made that last minute update.

**Comment by lennyAiko** [comment]
And now there is conflict @Ndohjapan 

You may need to update your local before making any changes

**Comment by lennyAiko** [comment]
Ok closing PR now

**Pull request closed without merging**
