### PR TITLE
Folder structure

### PR DESCRIPTION
**Pull request by oluwatobiloba1**
created the folder stucture again

### CODE REVIEW

**Comment by DominusKelvin** [comment]
@oluwatobiloba1 this is good but I've got a couple of things for you. First you are not using conventional commits, I think you need to go check that out :)

Also the naming of the files is using camelCase and we've discussed previously it should be hyphenated?

**Comment by oluwatobiloba1** [comment]
okay, i will quickly correct the file naming, and i will take notes of the commit, just forgot since there was no precommit linter on this project

**Comment by geekiedj** [comment]
Also @oluwatobiloba1 Kelvin mentioned adding the .spec.js extension to the commit file. For example; number-validator.spec.js

**Comment by oluwatobiloba1** [comment]
> Also @oluwatobiloba1 Kelvin mentioned adding the ".spec.js" extension to the commit file. For example; number-validator.spec.js

sorry i saw this late, i will look into that as well

**Comment by oluwatobiloba1** [comment]
@geekiedj is the current changes okay?

**Pull request closed without merging**
