### PR TITLE
feat(UI): revamp user interface

### PR DESCRIPTION
**Pull request by Vixs101**
So i fixed issue #58  by making Changes to the UI design of the web page and also adding a favicon in the head section and a table for the CSV file output

### CODE REVIEW

**Comment by lennyAiko** [comment]
Ok @Vixs101 , that is nice, no conflicts.

Can you indicate which issue you are fixing?

**Comment by geekiedj** [comment]
@Vixs101 Could you please provide screenshots of the revamped front end? It would help us evaluate the visual improvements you've made. Thank you!

**Comment by Vixs101** [comment]
> @Vixs101 Could you please provide screenshots of the revamped front end? It would help us evaluate the visual improvements you've made. Thank you!

Oh yeah, I did that on the discord server

**Comment by Vixs101** [comment]
> @Vixs101 Could you please provide screenshots of the revamped front end? It would help us evaluate the visual improvements you've made. Thank you!

here u go
Screenshot (146)
Screenshot (147)

**Pull request merged**
